_wandb:
    value:
        cli_version: 0.27.0
        e:
            iirouw4e598rieg98sknzuyz059rqglk:
                apple:
                    ecpuCores: 4
                    gpuCores: 10
                    macModel: Mac14,7
                    memoryGb: 16
                    name: Apple M2
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "2147483648"
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "494384795648"
                        used: "374569664512"
                email: dkjha0711@gmail.com
                executable: /Users/divyaanshjha/Desktop/ass_3/da6401_assignment_3/venv/bin/python
                git:
                    commit: 33b83d8dd395b4386b30893f949d4d715ec4798d
                    remote: https://github.com/Divyaansh0711/da6401_assignment_3.git
                host: Durgeshs-MacBook-Pro.local
                memory:
                    total: "17179869184"
                os: macOS-15.6-arm64-arm-64bit-Mach-O
                program: /Users/divyaanshjha/Desktop/ass_3/da6401_assignment_3/train.py
                python: CPython 3.13.0
                root: /Users/divyaanshjha/Desktop/ass_3/da6401_assignment_3
                startedAt: "2026-05-15T09:59:07.661707Z"
                writerId: iirouw4e598rieg98sknzuyz059rqglk
        m: []
        python_version: 3.13.0
        t:
            "1":
                - 1
                - 33
                - 49
                - 51
            "2":
                - 1
                - 33
                - 49
                - 51
            "3":
                - 16
            "4": 3.13.0
            "5": 0.27.0
            "12": 0.27.0
            "13": darwin-arm64
"N":
    value: 3
batch_size:
    value: 64
checkpoint_path:
    value: checkpoint.pt
d_ff:
    value: 512
d_model:
    value: 256
dropout:
    value: 0.1
label_smoothing:
    value: 0.1
lr:
    value: 1
max_len:
    value: 100
min_freq:
    value: 2
num_epochs:
    value: 10
num_heads:
    value: 8
vocab_path:
    value: vocabs.json
warmup_steps:
    value: 4000
